const tempPost = {
  id: 0,
  title: "Title",
  content: "",
  author: "Author",
  category: "Category",
  tag: ["Tag", "Tag", "Tag"],
  created_at: null,
  updated_at: null,
  views: 0,
  comments: [
    {
      id: 1,
      author: "id 1",
      content: "Temp Comment",
      created_at: null,
      updated_at: null,
      parent_id: null,
      replies: [
        {
          id: 1000001,
          author: "reply id 1-1",
          content: "reply Temp Comment",
          created_at: null,
          updated_at: null,
          parent_id: 1,
          replies: [],
        },
        {
          id: 1000002,
          author: "reply id 1-2",
          content: "reply Temp Comment2",
          created_at: null,
          updated_at: null,
          parent_id: 1,
          replies: [
            {
              id: 1000003,
              author: "reply reply id 1-2-1",
              content: "reply reply Temp Comment",
              created_at: null,
              updated_at: null,
              parent_id: 3,
              replies: [],
            },
          ],
        },
      ],
    },
    {
      id: 2,
      author: "id 2",
      content: "Temp Comment",
      created_at: null,
      updated_at: null,
      parent_id: null,
      replies: [],
    },
    {
      id: 3,
      author: "id 3",
      content: "Temp Comment",
      created_at: null,
      updated_at: null,
      parent_id: null,
      replies: [
        {
          id: 3000001,
          author: "reply id 3-1",
          content: "reply Temp Comment",
          created_at: null,
          updated_at: null,
          parent_id: 3,
          replies: [],
        },
      ],
    },
    {
      id: 4,
      author: "id 4",
      content: "Temp Comment",
      created_at: null,
      updated_at: null,
      parent_id: null,
      replies: [],
    },
  ],
};

export { tempPost };
